In [ ]:
print ("Hello World!")

Hello World!


In [ ]:
import numpy as np
a=np.ones((2,2))
print (a)

[[1. 1.]
 [1. 1.]]


In [ ]:
import numpy as np
a=np.ones((2,2))
print(a.size)

4


In [ ]:
import numpy as np
a=np.ones((2,2))
print(a.shape)

(2, 2)


In [ ]:
import numpy as np
a=np.random.randint(10,size=(2,2))
print (a)

[[5 0]
 [8 4]]


In [ ]:
import numpy as np
a=np.random.randint(10,size=(3,5))
print (a)
print ("Matriz con Reshape")
b=np.reshape(a,(5,3))
print (b)

[[3 8 4 8 5]
 [6 8 1 2 0]
 [1 5 7 0 5]]
Matriz con Reshape
[[3 8 4]
 [8 5 6]
 [8 1 2]
 [0 1 5]
 [7 0 5]]


In [ ]:
import numpy as np
a=np.random.randint(100,size=(5,5))
print (a)

tmp=a[2]
for i in range(0,5):
  a[2][i]=a[i][3]
  a[i][3]=tmp[2][i]

print (a)

[[56 29 79 78 96]
 [47 11 97 40 19]
 [41 67 81 38 68]
 [15  1 18 11  4]
 [40 30 90 38 21]]


IndexError: ignored

In [ ]:
import numpy as np
a=np.random.randint(100,size=(5,5))
print (a)

#INTERCAMBIAR COLUMNA 2 X FILA 3 EN UNA MATRIZ DE 5,5
tmp = np.copy(a[1])
a[1] = a[2]
a[2] = tmp

print (a)

[[ 7 68 28 29  1]
 [35 97 55 71 13]
 [22 58 49 17 89]
 [67 97  5 19 38]
 [90 37  3 67 74]]
[[ 7 68 28 29  1]
 [22 58 49 17 89]
 [35 97 55 71 13]
 [67 97  5 19 38]
 [90 37  3 67 74]]


In [6]:
import numpy

n = 8
m = 8
X = numpy.random.randint(0, 255, (n, m))

Y = numpy.array([[0, 1, 0],
                 [1, -4, 1],
                 [0, 1, 0]])

Z = numpy.zeros_like(X)

for i in range(1, n-1):
    for j in range(1, m-1):
        Z[i,j] = numpy.sum(X[i-1:i+2,j-1:j+2] * Y)

        if Z[i,j] > 255:
            Z[i,j] = 255
     
        elif Z[i,j] < 0:
            Z[i,j] = 0



Z[0,: ] = X[0,:]
Z[-1,:] = X[-1,:]
Z[:,0 ] = X[:,0]
Z[:,-1] = X[:,-1]  



print(Z)

[[ 17 182  21  81 179 229 148 205]
 [180   0   0   0   0 249 255 228]
 [238 255 255  73   0 255   0 247]
 [ 28   0   0 255 123   0   0 252]
 [201 255   0   0   0 255  26  57]
 [149   0 168   0  14   0   0 110]
 [106 255   0   0   0 255   0  68]
 [105  92  16  90 152 231 149  96]]
